version: "3.8"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=lelegoyeng
      - MYSQL_DATABASE=db_lelegoyeng
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-config:/etc/mysql

volumes:
  mysql-data:
  mysql-config:
#Public Key Retrieval is not allowed ? jangan lupa di setting true didrive
